cc = gcc
all : play_again0 play_again1 play_again2 play_again3

play_again0: play_again0.c
	$(cc) -o $@ play_again0.c

play_again1: play_again1.c
	$(cc) -o $@ play_again1.c

play_again2: play_again2.c
	$(cc) -o $@ play_again2.c

play_again3: play_again3.c
	$(cc) -o $@ play_again3.c

clean:
	rm -f *.o
	rm -f play_again0
	rm -f play_again1
	rm -f play_again2
	rm -f play_again3